In [9]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [10]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.4646, 0.5763, 0.5688, 0.0206],
        [0.3222, 0.1786, 0.1252, 0.0210],
        [0.9684, 0.3996, 0.5773, 0.9427]])
tensor([[-0.5971,  1.2388,  0.3316,  0.5848],
        [-2.7033, -0.2791,  0.0450, -0.1823],
        [ 0.1192,  1.3372, -0.0873,  1.6145]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [12]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


In [13]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[-1.0956,  0.6151,  0.7020,  0.0158, -0.2646],
         [-1.4622,  0.2803,  0.4857,  1.2073, -0.6852],
         [-0.8315,  1.3552, -1.9831,  0.8095,  0.5868],
         [ 1.4474,  0.8321,  1.0840, -0.8938,  0.5762]],

        [[ 0.2432,  2.6207, -0.4713, -0.5976,  2.0886],
         [ 1.2232,  1.6831, -0.3769,  0.5427,  0.5110],
         [-0.6550,  0.0759,  0.3734,  1.1714, -1.5213],
         [-0.9527, -0.8597, -0.5593,  0.7844, -0.2843]],

        [[ 0.8910,  0.3988,  1.6477,  1.0924,  0.4486],
         [ 0.5041, -0.5322,  0.0105,  1.6682,  2.4716],
         [ 0.5778, -0.6385,  0.4092, -1.0725, -0.6689],
         [-0.2107,  0.1516, -1.1126, -0.3069,  2.3397]]])

Tensor a[1]:
tensor([[ 0.2432,  2.6207, -0.4713, -0.5976,  2.0886],
        [ 1.2232,  1.6831, -0.3769,  0.5427,  0.5110],
        [-0.6550,  0.0759,  0.3734,  1.1714, -1.5213],
        [-0.9527, -0.8597, -0.5593,  0.7844, -0.2843]])

Tensor a[1:, 2:4]:
tensor([[[-0.6550,  0.0759,  0.3734,  1.1714, -1.5

In [25]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[-0.7911, -0.0209, -0.7185,  0.5186],
        [-1.3125,  0.1920,  0.5428, -2.2188],
        [ 0.2590, -1.0297, -0.5008,  0.2734]])

Flatten:
tensor([-0.7911, -0.0209, -0.7185,  0.5186, -1.3125,  0.1920,  0.5428, -2.2188,
         0.2590, -1.0297, -0.5008,  0.2734])

Reshape to 3 x 2 x 2:
tensor([[[-0.7911, -0.0209],
         [-0.7185,  0.5186]],

        [[-1.3125,  0.1920],
         [ 0.5428, -2.2188]],

        [[ 0.2590, -1.0297],
         [-0.5008,  0.2734]]])


In [15]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[-1.5061, -2.5657,  0.2779],
        [-1.4965, -1.4601,  0.7079]])
b:
tensor([[-0.5285,  0.3484, -1.9862],
        [-2.3525, -1.4632,  0.2236]])

a + b:
tensor([[-2.0345, -2.2173, -1.7083],
        [-3.8490, -2.9233,  0.9315]])

a / b:
tensor([[ 2.8499, -7.3647, -0.1399],
        [ 0.6361,  0.9979,  3.1662]])

a^2:
tensor([[2.2682, 6.5828, 0.0772],
        [2.2395, 2.1319, 0.5011]])

Matrix multiplication:
tensor([[-0.6498,  7.3592],
        [-1.1239,  5.8151]])


In [16]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[-0.6214, -0.0039, -1.1666, -0.0305],
        [-0.5554, -2.3938,  0.0686, -1.4923],
        [ 2.0765,  0.6556,  1.1867,  0.9154]])

Mean:
tensor([ 0.2999, -0.5807,  0.0296, -0.2025])

Standard deviation:
tensor([1.5390, 1.6045, 1.1771, 1.2130])

Cumulative sum:
tensor([[-0.6214, -0.0039, -1.1666, -0.0305],
        [-1.1768, -2.3977, -1.0980, -1.5227],
        [ 0.8997, -1.7421,  0.0887, -0.6074]])


In [17]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [21]:
import numpy as np
import torch

polynomial = np.poly1d([1, 2, 3])

N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-1.9483],
        [ 0.3272],
        [-0.5009]], requires_grad=True)
Learned coefficients:
tensor([[1.0056],
        [2.0230],
        [2.4637]], requires_grad=True)


In [28]:
import random
import torch

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4

    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A.item())
print("B =", B.item())
print("C =", C.item())
print("D =", D.item())

A = 4.741182327270508
B = 4.258769989013672
C = 3.2588000297546387
D = 2.2587828636169434


In [24]:
import numpy as np
import torch

torch.manual_seed(0)
np.random.seed(0)

# ---------- Câu 1: reshape ----------
print("=== Câu 1: reshape ===")
X = torch.arange(24)
print("X:", X)
print("4 x 6:\n", X.reshape(4, 6))
print("2 x 12:\n", X.reshape(2, 12))
print("2 x 3 x 4:\n", X.reshape(2, 3, 4))

# ---------- Câu 2: phép toán trên tensor ----------
print("\n=== Câu 2: phép toán trên tensor ===")
A = torch.randn(3, 4)
B = torch.randn(3, 4)
print("A:\n", A)
print("B:\n", B)
print("A + B:\n", A + B)
print("A * B:\n", A * B)
print("A / B:\n", A / B)
print("Trung bình theo cột:", A.mean(dim=0))
print("Độ lệch chuẩn theo cột:", A.std(dim=0))

# ---------- Câu 3: autograd ----------
print("\n=== Câu 3: autograd ===")
x = torch.tensor(2.0, requires_grad=True)
y = 2 * x**2 + 5 * x + 3
y.backward()
print("dy/dx tại x = 2 (autograd):", x.grad.item())
print("dy/dx tại x = 2 (thủ công, 4x + 5):", 4 * 2 + 5)

# ---------- Câu 4: huấn luyện đa thức y = 2x^2 - 3x + 5 ----------
print("\n=== Câu 4: học hệ số của y = 2x^2 - 3x + 5 ===")
polynomial = np.poly1d([2, -3, 5])

N = 20
Xn = np.random.randn(N, 1) * 5
Yn = polynomial(Xn)

XX = np.hstack([Xn * Xn, Xn, np.ones_like(Xn)])

w = torch.randn(3, 1, requires_grad=True)
x_t = torch.tensor(XX, dtype=torch.float32)
y_t = torch.tensor(Yn, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.05)

print("Hệ số ban đầu:", w.detach().flatten().tolist())

for epoch in range(5000):
    optimizer.zero_grad()
    y_pred = x_t @ w
    mse = torch.mean(torch.square(y_t - y_pred))
    mse.backward()
    optimizer.step()

print("Hệ số học được [a, b, c]:", w.detach().flatten().tolist())
print("Hệ số thực          :", [2, -3, 5])
print("MSE cuối:", mse.item())

=== Câu 1: reshape ===
X: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
4 x 6:
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
2 x 12:
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
2 x 3 x 4:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

=== Câu 2: phép toán trên tensor ===
A:
 tensor([[ 1.5410, -0.2934, -2.1788,  0.5684],
        [-1.0845, -1.3986,  0.4033,  0.8380],
        [-0.7193, -0.4033, -0.5966,  0.1820]])
B:
 tensor([[-0.8567,  1.1006, -1.0712,  0.1227],
        [-0.5663,  0.3731, -0.8920, -1.5091],
        [ 0.3704,  1.4565,  0.9398,  0.7748]])
A + B:
 tensor([[ 0.6843,  0.8072, -3.2500,  0.6911],
        [-1.6508, -1.0255, -0.4886